const video = [
  [
    {
      id: "0",
      name: "Тэма 1. Якую супольнасць мы ствараем.",
      name_eng: "Topic 1. What community we are creating.",
      src: "https://www.youtube.com/embed/0EwXNXLLn98",
    },
    {
      id: "1",
      name: "Тэма 2. Які базавы набор роляў ў супольнасці.",
      name_eng: "Topic 2. Bacis list of roles in community.",
      src: "https://www.youtube.com/embed/pvsjw4MTUHE",
    },
    {
      id: "2",
      name: "Тэма 3. Як далучаць новага ўдзельніка.",
      name_eng: "Topic 3. How to enlist new participants.",
      src: "https://www.youtube.com/embed/FR1T6cXsN4A",
    },
    {
      id: "3",
      name: "Тэма 4. Навошта ведаць межы супольнасці.",
      name_eng: "Topic 4. Why we need to know community borders.",
      src: "https://www.youtube.com/embed/cBGsPMt-2wo",
    },
    {
      id: "4",
      name: "Тэма 5. Як уплываюць культура, каштоўнасці і мэты на пабудову супольнасці.",
      name_eng: "Topic 5. How culture, values, and goals influence a community building process.",
      src: "https://www.youtube.com/embed/ckkP9AtxNOU",
    },
    {
      id: "5",
      name: "Тэма 6. Што рабіць з “лішнімі” людзьмі ў супольнасці.",
      name_eng: "Topic 6. What to do with “needless” people in a community.",
      src: "https://www.youtube.com/embed/JBVE6kN74gc",
    },
    {
      id: "6",
      name: "Тэма 7. Мала людзей. Якой велічыні групы дастаткова.",
      name_eng: "Topic 7. Few people, What size of group is optimal.",
      src: "https://www.youtube.com/embed/ULSDKgG0o9o",
    },
    {
      id: "7",
      name: "Тэма 8. Як прызначаюцца “кіраўнікі” і “выканаўцы” ў супольнасці.",
      name_eng: "Topic 8. How to appoint “boss” and “staff” in the community.",
      src: "https://www.youtube.com/embed/sNZYcQCMMIg",
    },
    {
      id: "8",
      name: "Тэма 9. Як адбываецца прыняцце рашэнняў у нефармальных супольнасцях.",
      name_eng: "Topic 9. How decision-making happens in informal communities.",
      src: "https://www.youtube.com/embed/64w0vrZkiK8",
    },
    {
      id: "9",
      name: "Тэма 10. Як і навошта арыентавацца ў этапах развіцця супольнасці.",
      name_eng: "Topic 10. How and why to navigate different stages of community development.",
      src: "https://www.youtube.com/embed/PGHPJaEAK-I",
    },
  ],
  [
    {
      id: "10",
      name: "Тэма 11. Вызначаем эфектыўнасць супольнасці.",
      name_eng: "Topic 11. Define community “effectiveness”.",
      src: "https://www.youtube.com/embed/lsBtJ5ztKGU",
    },
    {
      id: "11",
      name: "Тэма 12. З чаго складаюцца рэсурсы супольнасці, і як імі кіраваць.",
      name_eng: "Topic 12. The composition of the community-pool resource. ",
      src: "https://www.youtube.com/embed/6fwV0lzjiq0",
    },
    {
      id: "12",
      name: "Тэма 13. Сімвалічны рэсурс: знакі, гісторыі і слоўнікі.",
      name_eng: "Topic 13. Symbolic resource: signs, histories, and vocabulary.",
      src: "https://www.youtube.com/embed/4uflfpM1erY",
    },
    {
      id: "13",
      name: "Тэма 14. Кантралюем рост універсальных і спецыялізаваных супольнасцяў.",
      name_eng: "Topic 14. Growth control of universal and specialized communities.",
      src: "https://www.youtube.com/embed/JyfguKEGi5U",
    },
    {
      id: "14",
      name: "Тэма 15. Чаму ўзнікае патрэба ў змене дзейнасці.",
      name_eng: "Topic 15. Why need to change agency appears.",
      src: "https://www.youtube.com/embed/jA98emVzoHo",
    },
    {
      id: "15",
      name: "Тэма 16. Што варта рабіць з колам прыхільнікаў.",
      name_eng: "Topic 16. What to do with circle of followers.",
      src: "https://www.youtube.com/embed/zGdPovjNE0A",
    },
    {
      id: "16",
      name: "Тэма 17.  Месца сацыятэхніка ў суполцы.",
      name_eng: "Topic 17. Where in community sociatechnician is.",
      src: "https://www.youtube.com/embed/QrXk6oXCJIY",
    },
    {
      id: "17",
      name: "Тэма 18.  Будуем доўгатэрміновыя адносіны паміж супольнасцямі.",
      name_eng: "Topic 18. Build long-term relations between communities.",
      src: "https://www.youtube.com/embed/yLKvPzXN1F4",
    },
    {
      id: "18",
      name: "Тэма 19.  ТОП-9 прычын. Чаму супольнасць змяншаецца.",
      name_eng: "Topic 19. TOP-9 reasons why community decreases.",
      src: "https://www.youtube.com/embed/_DVsD6S483E",
    },
    {
      id: "19",
      name: "Тэма 20. Хто і як вызначае ролі ў суполцы на розных этапах яе жыцця.",
      name_eng: "Topic 20. Who and how defines community roles on different stages of its lifespan.",
      src: "https://www.youtube.com/embed/mt-LWDAlruI",
    },
  ],
  [
    {
      id: "20",
      name: "Тэма 21. Імунітэт супольнасці. Як cупольнасці пазбаўляюцца ад непатрэбнага ўплыву або таксічных удзельнікаў.",
      name_eng: "Topic 21. Community immunity. How communities eliminate destructive influence or toxic participants.",
      src: "https://www.youtube.com/embed/z-DtdeLt1V4",
    },
    {
      id: "21",
      name: "Тэма 22.  Этап зрэласці. Як вырашаць канфлікты ў супольнасці.",
      name_eng: "Topic 22. Maturity stage. How to solve conflicts inside a community.",
      src: "https://www.youtube.com/embed/VoYenLZXqhg",
    },
    {
      id: "22",
      name: "Тэма 23. Давер і аўтарытэт у супольнасці на розных этапах жыцця.",
      name_eng: "Topic 23. Trust and respectfulness in a community on different stages of a lifespan.",
      src: "https://www.youtube.com/embed/PIuhrLv0Nnk",
    },
    {
      id: "23",
      name: "Тэма 24. Інтэлектуальны рэсурс. Перадача ведаў. Чаму не абыйсціся без дакументавання дзейнасці і досведу.",
      name_eng: "Topic 24. Intellectual resource. Knowledge transfer. Why not to avoid documenting activities and experience.",
      src: "https://www.youtube.com/embed/bHUHLxRjgXA",
    },
    {
      id: "24",
      name: "Тэма 25. Унутраная структура. Навошта разумець гарызантальную і вертыкальную іерархію ў групе. Калектыўнае і адзінаасобнае лідэрства.",
      name_eng: "Topic 25. Internal structure. Why to know horizontal and vertical hierarchy in a group. Collective and personal leadership.",
      src: "https://www.youtube.com/embed/qEnFvHUBK_w",
    },
    {
      id: "25",
      name: "Тэма 26. Калі патрэбна фармальная арганізацыя супольнасці. Яе месца і функцыі.",
      name_eng: "Topic 26. When formal organization for a community is necessary. Its place and functions.",
      src: "https://www.youtube.com/embed/RyXqBMj-BMI",
    },
    {
      id: "26",
      name: "Тэма 27.  Што рабіць з канкуруючымі і капліментарнымі супольнасцямі.",
      name_eng: "Topic 27. What to do with rival and complementary communities. ",
      src: "https://www.youtube.com/embed/m79wsZzHQPM",
    },
    {
      id: "27",
      name: "Тэма 28.  Рост і зрэласць. Плюсы і мінусы шматядзерных супольнасцяў.",
      name_eng: "Topic 28. Growth and maturity. Pluses and drawbacks in multicore communities.",
      src: "https://www.youtube.com/embed/xsXBVAt4Z6w",
    },
    {
      id: "28",
      name: "Тэма 29. Супольнасць супольнасцяў. Ці магчыма асамблея суполак.",
      name_eng: "Topic 29. Community of communities. Is it possible to make an assembly of communities?",
      src: "https://www.youtube.com/embed/ZcuMN6LYMFc",
    },
    {
      id: "29",
      name: "Тэма 30. Заключная лекцыя.",
      name_eng: "Topic 30. Conclusion.",
      src: "https://www.youtube.com/embed/twHnvehrfi8",
    },
  ],
];

export default video;
